global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'authorizationservice'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['authorizationservice:7178']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
