services:
  authorizationservice:
    container_name: authservice-authorizationservice
    image: ${DOCKER_REGISTRY-}authorizationservice
    build:
      context: .
      dockerfile: Sample.AuthorizationService.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5234
      - ASPNETCORE_HTTPS_PORTS=7178
    ports:
      - '5234:5234'
      - '7178:7178'
    volumes:
      - ./logs:/logs/samples/authorizationservice
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https:ro

  mssqldb:
    container_name: authservice-mssqldb
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: '#&E*ye76t&#YGet8q7#*&YTtw8qytt&E7t378ET78etW*87'
      ACCEPT_EULA: 'Y'
    ports:
      - '1433:1433'

  prometheus:
    container_name: authservice-prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus-data:/prometheus

  grafana:
    container_name: authservice-grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    ports:
      - 3000:3000
    volumes:
      - ./grafana-data:/var/lib/grafana

  node-exporter:
    container_name: authservice-node-exporter
    image: quay.io/prometheus/node-exporter:latest
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  # elasticsearchserver:
  #   image: elasticsearch:7.15.1
  #   ports:
  #     - 9200:9200
  #   environment:
  #     - discovery.type=single-node
  #   volumes:
  #     - ../elasticsearch/data:/usr/share/elasticsearch/data

  # kibanaserver:
  #   image: kibana:7.15.1
  #   ports:
  #     - 5601:5601
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
