using Sample.AuthorizationService.Common.Enums;
using Sample.AuthorizationService.Common.ResponseModels;

namespace Sample.AuthorizationService.Common.Defaults;

internal static class UsersDefaults
{
    internal const string Password = "sDyd982HS8s6H&%h62Hgs8^#!12bySmS2873SY&*EGHDTRuydsTT&D";

    internal static readonly IEnumerable<UserDetails> Users = new[]
    {
        new UserDetails
        {
            Id = 1,
            FamilyName = "Smith",
            GivenName = "John",
            Nickname = "John",
            ZoneInfo = "Europe/London",
            Gender = Gender.Male,
            Locale = "en-GB",
            Email = "j2XvU@example.com",
            PhoneNumber = "+44 1234567890",
            BirthDate = DateTime.Parse("1980-01-01"),
            Role = Role.Admin,
        },
        new UserDetails
        {
            Id = 2,
            FamilyName = "Doe",
            GivenName = "Jane",
            Nickname = "Jane",
            ZoneInfo = "America/New_York",
            Gender = Gender.Female,
            Locale = "en-US",
            Email = "jane.doe@example.com",
            PhoneNumber = "+1 9876543210",
            BirthDate = DateTime.Parse("1990-05-15"),
            Role = Role.Admin,
        },
        new UserDetails
        {
            Id = 3,
            FamilyName = "Johnson",
            GivenName = "Michael",
            Nickname = "Mike",
            ZoneInfo = "America/Los_Angeles",
            Gender = Gender.Male,
            Locale = "en-US",
            Email = "mike.johnson@example.com",
            PhoneNumber = "+1 5555555555",
            BirthDate = DateTime.Parse("1995-08-20"),
            Role = Role.Admin, 
        },
        new UserDetails
        {
            Id = 4,
            FamilyName = "Williams",
            GivenName = "Emily",
            Nickname = "Em",
            ZoneInfo = "Australia/Sydney",
            Gender = Gender.Female,
            Locale = "en-AU",
            Email = "emily.williams@example.com",
            PhoneNumber = "+61 123456789",
            BirthDate = DateTime.Parse("1988-12-10"),
            Role = Role.Admin, 
        },
        new UserDetails
        {
            Id = 5,
            FamilyName = "Brown",
            GivenName = "Sarah",
            Nickname = "Sara",
            ZoneInfo = "Asia/Tokyo",
            Gender = Gender.Female,
            Locale = "ja-JP",
            Email = "sarah.brown@example.com",
            PhoneNumber = "+81 987654321",
            BirthDate = DateTime.Parse("1992-03-25"),
            Role = Role.Admin, 
        },
        new UserDetails
        {
            Id = 6,
            FamilyName = "Garcia",
            GivenName = "Carlos",
            Nickname = "Carl",
            ZoneInfo = "America/Chicago",
            Gender = Gender.Male,
            Locale = "es-MX",
            Email = "carlos.garcia@example.com",
            PhoneNumber = "+52 1234567890",
            BirthDate = DateTime.Parse("1985-07-12"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 7,
            FamilyName = "Lee",
            GivenName = "Ji-hyun",
            Nickname = "Ji",
            ZoneInfo = "Asia/Seoul",
            Gender = Gender.Female,
            Locale = "ko-KR",
            Email = "ji-hyun.lee@example.com",
            PhoneNumber = "+82 987654321",
            BirthDate = DateTime.Parse("1998-11-05"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 8,
            FamilyName = "Martinez",
            GivenName = "Luis",
            Nickname = "Lucho",
            ZoneInfo = "America/Bogota",
            Gender = Gender.Male,
            Locale = "es-CO",
            Email = "luis.martinez@example.com",
            PhoneNumber = "+57 1234567890",
            BirthDate = DateTime.Parse("1993-09-18"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 9,
            FamilyName = "Wang",
            GivenName = "Wei",
            Nickname = "William",
            ZoneInfo = "Asia/Shanghai",
            Gender = Gender.Male,
            Locale = "zh-CN",
            Email = "wei.wang@example.com",
            PhoneNumber = "+86 1234567890",
            BirthDate = DateTime.Parse("1989-06-30"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 10,
            FamilyName = "Lopez",
            GivenName = "Maria",
            Nickname = "Marie",
            ZoneInfo = "America/Mexico_City",
            Gender = Gender.Female,
            Locale = "es-MX",
            Email = "maria.lopez@example.com",
            PhoneNumber = "+52 9876543210",
            BirthDate = DateTime.Parse("1996-02-15"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 11,
            FamilyName = "Nguyen",
            GivenName = "Huyen",
            Nickname = "Huyen",
            ZoneInfo = "Asia/Ho_Chi_Minh",
            Gender = Gender.Female,
            Locale = "vi-VN",
            Email = "huyen.nguyen@example.com",
            PhoneNumber = "+84 987654321",
            BirthDate = DateTime.Parse("1994-04-10"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 12,
            FamilyName = "Kim",
            GivenName = "Sung-hyun",
            Nickname = "Sung",
            ZoneInfo = "Asia/Seoul",
            Gender = Gender.Male,
            Locale = "ko-KR",
            Email = "sung-hyun.kim@example.com",
            PhoneNumber = "+82 987654321",
            BirthDate = DateTime.Parse("1997-12-20"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 13,
            FamilyName = "Gonzalez",
            GivenName = "Ana",
            Nickname = "Annie",
            ZoneInfo = "America/Mexico_City",
            Gender = Gender.Female,
            Locale = "es-MX",
            Email = "ana.gonzalez@example.com",
            PhoneNumber = "+52 1234567890",
            BirthDate = DateTime.Parse("1991-08-05"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 14,
            FamilyName = "Chen",
            GivenName = "Wei",
            Nickname = "David",
            ZoneInfo = "Asia/Shanghai",
            Gender = Gender.Male,
            Locale = "zh-CN",
            Email = "wei.chen@example.com",
            PhoneNumber = "+86 1234567890",
            BirthDate = DateTime.Parse("1990-03-15"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 15,
            FamilyName = "Hernandez",
            GivenName = "Alejandra",
            Nickname = "Ale",
            ZoneInfo = "America/Mexico_City",
            Gender = Gender.Female,
            Locale = "es-MX",
            Email = "alejandra.hernandez@example.com",
            PhoneNumber = "+52 9876543210",
            BirthDate = DateTime.Parse("1993-09-25"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 16,
            FamilyName = "Li",
            GivenName = "Xia",
            Nickname = "Lucy",
            ZoneInfo = "Asia/Shanghai",
            Gender = Gender.Female,
            Locale = "zh-CN",
            Email = "xia.li@example.com",
            PhoneNumber = "+86 1234567890",
            BirthDate = DateTime.Parse("1994-06-12"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 17,
            FamilyName = "Gupta",
            GivenName = "Rahul",
            Nickname = "Rah",
            ZoneInfo = "Asia/Kolkata",
            Gender = Gender.Male,
            Locale = "en-IN",
            Email = "rahul.gupta@example.com",
            PhoneNumber = "+91 9876543210",
            BirthDate = DateTime.Parse("1987-11-30"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 18,
            FamilyName = "Kim",
            GivenName = "Min-ji",
            Nickname = "Minnie",
            ZoneInfo = "Asia/Seoul",
            Gender = Gender.Female,
            Locale = "ko-KR",
            Email = "min-ji.kim@example.com",
            PhoneNumber = "+82 987654321",
            BirthDate = DateTime.Parse("1996-02-25"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 19,
            FamilyName = "Kumar",
            GivenName = "Amit",
            Nickname = "Ami",
            ZoneInfo = "Asia/Kolkata",
            Gender = Gender.Male,
            Locale = "en-IN",
            Email = "amit.kumar@example.com",
            PhoneNumber = "+91 9876543210",
            BirthDate = DateTime.Parse("1992-09-10"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 20,
            FamilyName = "Lopez",
            GivenName = "Carolina",
            Nickname = "Caro",
            ZoneInfo = "America/Mexico_City",
            Gender = Gender.Female,
            Locale = "es-MX",
            Email = "carolina.lopez@example.com",
            PhoneNumber = "+52 1234567890",
            BirthDate = DateTime.Parse("1990-07-20"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 21,
            FamilyName = "Wong",
            GivenName = "Li",
            Nickname = "Lily",
            ZoneInfo = "Asia/Hong_Kong",
            Gender = Gender.Female,
            Locale = "zh-HK",
            Email = "li.wong@example.com",
            PhoneNumber = "+852 98765432",
            BirthDate = DateTime.Parse("1993-05-18"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 22,
            FamilyName = "Lee",
            GivenName = "Alex",
            Nickname = "ALee",
            ZoneInfo = "America/Los_Angeles",
            Gender = Gender.Male,
            Locale = "en-US",
            Email = "alex.lee@example.com",
            PhoneNumber = "+1 9876543210",
            BirthDate = DateTime.Parse("1991-06-18"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 23,
            FamilyName = "Gonzalez",
            GivenName = "Maria",
            Nickname = "Mari",
            ZoneInfo = "America/Mexico_City",
            Gender = Gender.Female,
            Locale = "es-MX",
            Email = "maria.gonzalez@example.com",
            PhoneNumber = "+52 1234567890",
            BirthDate = DateTime.Parse("1995-09-15"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 24,
            FamilyName = "Alvarez",
            GivenName = "Pablo",
            Nickname = "PAlvarez",
            ZoneInfo = "America/Mexico_City",
            Gender = Gender.Male,
            Locale = "es-MX",
            Email = "pablo.alvarez@example.com",
            PhoneNumber = "+52 123456789",
            BirthDate = DateTime.Parse("1990-09-12"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 25,
            FamilyName = "Lee",
            GivenName = "Min-woo",
            Nickname = "Min",
            ZoneInfo = "Asia/Seoul",
            Gender = Gender.Male,
            Locale = "ko-KR",
            Email = "min-woo.lee@example.com",
            PhoneNumber = "+82 987654321",
            BirthDate = DateTime.Parse("1988-08-08"),
            Role = Role.Moderator,
        },
        new UserDetails
        {
            Id = 26,
            FamilyName = "Patel",
            GivenName = "Priya",
            Nickname = "Pri",
            ZoneInfo = "Asia/Kolkata",
            Gender = Gender.Female,
            Locale = "en-IN",
            Email = "priya.patel@example.com",
            PhoneNumber = "+91 9876543210",
            BirthDate = DateTime.Parse("1993-03-25"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 27,
            FamilyName = "Hernandez",
            GivenName = "Luis",
            Nickname = "Lucho",
            ZoneInfo = "America/Mexico_City",
            Gender = Gender.Male,
            Locale = "es-MX",
            Email = "luis.hernandez@example.com",
            PhoneNumber = "+52 1234567890",
            BirthDate = DateTime.Parse("1991-12-05"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 28,
            FamilyName = "Wang",
            GivenName = "Xiao",
            Nickname = "Xia",
            ZoneInfo = "Asia/Shanghai",
            Gender = Gender.Female,
            Locale = "zh-CN",
            Email = "xiao.wang@example.com",
            PhoneNumber = "+86 1234567890",
            BirthDate = DateTime.Parse("1992-07-30"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 29,
            FamilyName = "Kim",
            GivenName = "Ji-hoon",
            Nickname = "Hoon",
            ZoneInfo = "Asia/Seoul",
            Gender = Gender.Male,
            Locale = "ko-KR",
            Email = "ji-hoon.kim@example.com",
            PhoneNumber = "+82 987654321",
            BirthDate = DateTime.Parse("1989-09-12"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 30,
            FamilyName = "Choudhury",
            GivenName = "Ayesha",
            Nickname = "Aya",
            ZoneInfo = "Asia/Kolkata",
            Gender = Gender.Female,
            Locale = "en-IN",
            Email = "ayesha.choudhury@example.com",
            PhoneNumber = "+91 9876543210",
            BirthDate = DateTime.Parse("1994-10-08"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 31,
            FamilyName = "Garcia",
            GivenName = "Isabella",
            Nickname = "Bella",
            ZoneInfo = "America/New_York",
            Gender = Gender.Female,
            Locale = "en-US",
            Email = "isabella.garcia@example.com",
            PhoneNumber = "+1 5555555555",
            BirthDate = DateTime.Parse("1993-02-14"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 32,
            FamilyName = "Nguyen",
            GivenName = "Anh",
            Nickname = "Annie",
            ZoneInfo = "Asia/Ho_Chi_Minh",
            Gender = Gender.Female,
            Locale = "vi-VN",
            Email = "anh.nguyen@example.com",
            PhoneNumber = "+84 987654321",
            BirthDate = DateTime.Parse("1990-06-30"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 33,
            FamilyName = "Lopez",
            GivenName = "Juan",
            Nickname = "Juani",
            ZoneInfo = "America/Mexico_City",
            Gender = Gender.Male,
            Locale = "es-MX",
            Email = "juan.lopez@example.com",
            PhoneNumber = "+52 1234567890",
            BirthDate = DateTime.Parse("1988-12-20"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 34,
            FamilyName = "Rossi",
            GivenName = "Matteo",
            Nickname = "MRossi",
            ZoneInfo = "Europe/Rome",
            Gender = Gender.Male,
            Locale = "it-IT",
            Email = "matteo.rossi@example.com",
            PhoneNumber = "+39 123456789",
            BirthDate = DateTime.Parse("1992-03-18"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 35,
            FamilyName = "Lee",
            GivenName = "Soo-jin",
            Nickname = "Soo",
            ZoneInfo = "Asia/Seoul",
            Gender = Gender.Female,
            Locale = "ko-KR",
            Email = "soo-jin.lee@example.com",
            PhoneNumber = "+82 987654321",
            BirthDate = DateTime.Parse("1996-04-05"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 36,
            FamilyName = "Kumar",
            GivenName = "Rahul",
            Nickname = "Rahul",
            ZoneInfo = "Asia/Kolkata",
            Gender = Gender.Male,
            Locale = "en-IN",
            Email = "rahul.kumar@example.com",
            PhoneNumber = "+91 9876543210",
            BirthDate = DateTime.Parse("1992-09-18"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 37,
            FamilyName = "Rodriguez",
            GivenName = "Sofia",
            Nickname = "Sofi",
            ZoneInfo = "America/New_York",
            Gender = Gender.Female,
            Locale = "en-US",
            Email = "sofia.rodriguez@example.com",
            PhoneNumber = "+1 5555555555",
            BirthDate = DateTime.Parse("1993-07-12"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 38,
            FamilyName = "Tran",
            GivenName = "Thi",
            Nickname = "Thi",
            ZoneInfo = "Asia/Ho_Chi_Minh",
            Gender = Gender.Female,
            Locale = "vi-VN",
            Email = "thi.tran@example.com",
            PhoneNumber = "+84 987654321",
            BirthDate = DateTime.Parse("1991-04-02"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 39,
            FamilyName = "Gomez",
            GivenName = "Miguel",
            Nickname = "Miguel",
            ZoneInfo = "America/Mexico_City",
            Gender = Gender.Male,
            Locale = "es-MX",
            Email = "miguel.gomez@example.com",
            PhoneNumber = "+52 1234567890",
            BirthDate = DateTime.Parse("1989-02-28"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 40,
            FamilyName = "Wu",
            GivenName = "Yan",
            Nickname = "Yan",
            ZoneInfo = "Asia/Shanghai",
            Gender = Gender.Female,
            Locale = "zh-CN",
            Email = "yan.wu@example.com",
            PhoneNumber = "+86 1234567890",
            BirthDate = DateTime.Parse("1990-08-10"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 41,
            FamilyName = "Wilson",
            GivenName = "David",
            Nickname = "David",
            ZoneInfo = "America/New_York",
            Gender = Gender.Male,
            Locale = "en-US",
            Email = "david.wilson@example.com",
            PhoneNumber = "+1 123456789",
            BirthDate = DateTime.Parse("1985-09-20"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 42,
            FamilyName = "Gupta",
            GivenName = "Aman",
            Nickname = "Aman",
            ZoneInfo = "Asia/Kolkata",
            Gender = Gender.Male,
            Locale = "en-IN",
            Email = "aman.gupta@example.com",
            PhoneNumber = "+91 9876543210",
            BirthDate = DateTime.Parse("1992-03-15"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 43,
            FamilyName = "Martinez",
            GivenName = "Diego",
            Nickname = "Diego",
            ZoneInfo = "America/New_York",
            Gender = Gender.Male,
            Locale = "en-US",
            Email = "diego.martinez@example.com",
            PhoneNumber = "+1 5555555555",
            BirthDate = DateTime.Parse("1994-09-08"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 44,
            FamilyName = "Nguyen",
            GivenName = "Linh",
            Nickname = "Linh",
            ZoneInfo = "Asia/Ho_Chi_Minh",
            Gender = Gender.Female,
            Locale = "vi-VN",
            Email = "linh.nguyen@example.com",
            PhoneNumber = "+84 987654321",
            BirthDate = DateTime.Parse("1993-05-25"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 45,
            FamilyName = "Lopez",
            GivenName = "Santiago",
            Nickname = "Santi",
            ZoneInfo = "America/Mexico_City",
            Gender = Gender.Male,
            Locale = "es-MX",
            Email = "santiago.lopez@example.com",
            PhoneNumber = "+52 1234567890",
            BirthDate = DateTime.Parse("1990-12-03"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 46,
            FamilyName = "Zhang",
            GivenName = "Wei",
            Nickname = "Wei",
            ZoneInfo = "Asia/Shanghai",
            Gender = Gender.Male,
            Locale = "zh-CN",
            Email = "wei.zhang@example.com",
            PhoneNumber = "+86 1234567890",
            BirthDate = DateTime.Parse("1988-06-28"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 47,
            FamilyName = "Park",
            GivenName = "Ji-hye",
            Nickname = "Ji",
            ZoneInfo = "Asia/Seoul",
            Gender = Gender.Female,
            Locale = "ko-KR",
            Email = "ji-hye.park@example.com",
            PhoneNumber = "+82 987654321",
            BirthDate = DateTime.Parse("1997-01-10"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 48,
            FamilyName = "Kumar",
            GivenName = "Rajesh",
            Nickname = "Raj",
            ZoneInfo = "Asia/Kolkata",
            Gender = Gender.Male,
            Locale = "en-IN",
            Email = "rajesh.kumar@example.com",
            PhoneNumber = "+91 9876543210",
            BirthDate = DateTime.Parse("1991-08-22"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 49,
            FamilyName = "Sanchez",
            GivenName = "Ana",
            Nickname = "Ana",
            ZoneInfo = "America/New_York",
            Gender = Gender.Female,
            Locale = "en-US",
            Email = "ana.sanchez@example.com",
            PhoneNumber = "+1 5555555555",
            BirthDate = DateTime.Parse("1992-12-05"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 50,
            FamilyName = "Tran",
            GivenName = "Lan",
            Nickname = "Lan",
            ZoneInfo = "Asia/Ho_Chi_Minh",
            Gender = Gender.Female,
            Locale = "vi-VN",
            Email = "lan.tran@example.com",
            PhoneNumber = "+84 987654321",
            BirthDate = DateTime.Parse("1994-03-17"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 51,
            FamilyName = "Gonzalez",
            GivenName = "Carlos",
            Nickname = "Carlos",
            ZoneInfo = "America/Mexico_City",
            Gender = Gender.Male,
            Locale = "es-MX",
            Email = "carlos.gonzalez@example.com",
            PhoneNumber = "+52 1234567890",
            BirthDate = DateTime.Parse("1987-04-14"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 52,
            FamilyName = "Li",
            GivenName = "Chen",
            Nickname = "Chen",
            ZoneInfo = "Asia/Shanghai",
            Gender = Gender.Male,
            Locale = "zh-CN",
            Email = "chen.li@example.com",
            PhoneNumber = "+86 1234567890",
            BirthDate = DateTime.Parse("1989-10-30"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 53,
            FamilyName = "Williams",
            GivenName = "James",
            Nickname = "JWilliams",
            ZoneInfo = "America/Los_Angeles",
            Gender = Gender.Male,
            Locale = "en-US",
            Email = "james.williams@example.com",
            PhoneNumber = "+1 9876543210",
            BirthDate = DateTime.Parse("1991-06-18"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 54,
            FamilyName = "Singh",
            GivenName = "Amit",
            Nickname = "Amit",
            ZoneInfo = "Asia/Kolkata",
            Gender = Gender.Male,
            Locale = "en-IN",
            Email = "amit.singh@example.com",
            PhoneNumber = "+91 9876543210",
            BirthDate = DateTime.Parse("1993-07-08"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 55,
            FamilyName = "Brown",
            GivenName = "Olivia",
            Nickname = "Liv",
            ZoneInfo = "America/New_York",
            Gender = Gender.Female,
            Locale = "en-US",
            Email = "olivia.brown@example.com",
            PhoneNumber = "+1 5555555555",
            BirthDate = DateTime.Parse("1995-04-26"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 56,
            FamilyName = "Nguyen",
            GivenName = "Thi",
            Nickname = "Thi",
            ZoneInfo = "Asia/Ho_Chi_Minh",
            Gender = Gender.Female,
            Locale = "vi-VN",
            Email = "thi.nguyen@example.com",
            PhoneNumber = "+84 987654321",
            BirthDate = DateTime.Parse("1998-09-12"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 57,
            FamilyName = "Rodriguez",
            GivenName = "Miguel",
            Nickname = "Miguel",
            ZoneInfo = "America/Mexico_City",
            Gender = Gender.Male,
            Locale = "es-MX",
            Email = "miguel.rodriguez@example.com",
            PhoneNumber = "+52 1234567890",
            BirthDate = DateTime.Parse("1986-11-07"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 58,
            FamilyName = "Korhonen",
            GivenName = "Markus",
            Nickname = "MKorhonen",
            ZoneInfo = "Europe/Helsinki",
            Gender = Gender.Male,
            Locale = "fi-FI",
            Email = "markus.korhonen@example.com",
            PhoneNumber = "+358 123456789",
            BirthDate = DateTime.Parse("1991-06-25"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 59,
            FamilyName = "Lee",
            GivenName = "Eun-ji",
            Nickname = "Eun",
            ZoneInfo = "Asia/Seoul",
            Gender = Gender.Female,
            Locale = "ko-KR",
            Email = "eun-ji.lee@example.com",
            PhoneNumber = "+82 987654321",
            BirthDate = DateTime.Parse("1993-08-19"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 60,
            FamilyName = "Sharma",
            GivenName = "Rahul",
            Nickname = "Rahul",
            ZoneInfo = "Asia/Kolkata",
            Gender = Gender.Male,
            Locale = "en-IN",
            Email = "rahul.sharma@example.com",
            PhoneNumber = "+91 9876543210",
            BirthDate = DateTime.Parse("1994-12-31"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 61,
            FamilyName = "Novák",
            GivenName = "János",
            Nickname = "Jani",
            ZoneInfo = "Europe/Budapest",
            Gender = Gender.Male,
            Locale = "hu-HU",
            Email = "janos.novak@example.com",
            PhoneNumber = "+36 123456789",
            BirthDate = DateTime.Parse("1992-05-15"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 62,
            FamilyName = "Kowalska",
            GivenName = "Marta",
            Nickname = "Marta",
            ZoneInfo = "Europe/Warsaw",
            Gender = Gender.Female,
            Locale = "pl-PL",
            Email = "marta.kowalska@example.com",
            PhoneNumber = "+48 987654321",
            BirthDate = DateTime.Parse("1995-09-20"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 63,
            FamilyName = "Ivanov",
            GivenName = "Dmitry",
            Nickname = "Dima",
            ZoneInfo = "Asia/Almaty",
            Gender = Gender.Male,
            Locale = "ru-RU",
            Email = "dmitry.ivanov@example.com",
            PhoneNumber = "+7 9876543210",
            BirthDate = DateTime.Parse("1998-02-10"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 64,
            FamilyName = "Janković",
            GivenName = "Ana",
            Nickname = "Ana",
            ZoneInfo = "Europe/Belgrade",
            Gender = Gender.Female,
            Locale = "sr-RS",
            Email = "ana.jankovic@example.com",
            PhoneNumber = "+381 123456789",
            BirthDate = DateTime.Parse("1990-11-28"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 65,
            FamilyName = "Kovács",
            GivenName = "Gábor",
            Nickname = "Gabi",
            ZoneInfo = "Europe/Budapest",
            Gender = Gender.Male,
            Locale = "hu-HU",
            Email = "gabor.kovacs@example.com",
            PhoneNumber = "+36 987654321",
            BirthDate = DateTime.Parse("1993-07-02"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 66,
            FamilyName = "Smith",
            GivenName = "Taylor",
            Nickname = "TSmith",
            ZoneInfo = "America/Los_Angeles",
            Gender = Gender.Female,
            Locale = "en-US",
            Email = "taylor.smith@example.com",
            PhoneNumber = "+1 9876543210",
            BirthDate = DateTime.Parse("1992-09-12"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 67,
            FamilyName = "Johnson",
            GivenName = "Emily",
            Nickname = "Emily",
            ZoneInfo = "America/Chicago",
            Gender = Gender.Female,
            Locale = "en-US",
            Email = "emily.johnson@example.com",
            PhoneNumber = "+1 5555555555",
            BirthDate = DateTime.Parse("1995-05-18"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 68,
            FamilyName = "Larsson",
            GivenName = "Emma",
            Nickname = "ELarsson",
            ZoneInfo = "Europe/Stockholm",
            Gender = Gender.Female,
            Locale = "sv-SE",
            Email = "emma.larsson@example.com",
            PhoneNumber = "+46 123456789",
            BirthDate = DateTime.Parse("1995-03-25"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 69,
            FamilyName = "Skaryna",
            GivenName = "Uladzimir",
            Nickname = "Skaryna",
            ZoneInfo = "Europe/Minsk",
            Gender = Gender.Male,
            Locale = "be-BY",
            Email = "uladzimir.skaryna@example.com",
            PhoneNumber = "+375 987654328",
            BirthDate = DateTime.Parse("1997-12-03"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 70,
            FamilyName = "González",
            GivenName = "Manuel",
            Nickname = "Manuel",
            ZoneInfo = "America/Mexico_City",
            Gender = Gender.Male,
            Locale = "es-MX",
            Email = "manuel.gonzalez@example.com",
            PhoneNumber = "+52 1234567890",
            BirthDate = DateTime.Parse("1991-11-21"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 71,
            FamilyName = "Kovačević",
            GivenName = "Ana",
            Nickname = "Ana",
            ZoneInfo = "Europe/Belgrade",
            Gender = Gender.Female,
            Locale = "sr-RS",
            Email = "ana.kovacevic@example.com",
            PhoneNumber = "+381 123456789",
            BirthDate = DateTime.Parse("1994-07-07"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 72,
            FamilyName = "Hansen",
            GivenName = "Emma",
            Nickname = "EHansen",
            ZoneInfo = "Europe/Copenhagen",
            Gender = Gender.Female,
            Locale = "da-DK",
            Email = "emma.hansen@example.com",
            PhoneNumber = "+45 12345678",
            BirthDate = DateTime.Parse("1994-08-07"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 73,
            FamilyName = "Li",
            GivenName = "Wei",
            Nickname = "Wei",
            ZoneInfo = "Asia/Shanghai",
            Gender = Gender.Male,
            Locale = "zh-CN",
            Email = "wei.li@example.com",
            PhoneNumber = "+86 1234567890",
            BirthDate = DateTime.Parse("1994-11-10"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 74,
            FamilyName = "Popov",
            GivenName = "Alexei",
            MiddleName = "Ivanovich",
            Nickname = "Alex",
            ZoneInfo = "Europe/Paris",
            Gender = Gender.Male,
            Locale = "ru-RU",
            Email = "alexei.popov@example.com",
            PhoneNumber = "+1 1234567890",
            BirthDate = DateTime.Parse("1993-03-15"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 75,
            FamilyName = "Kovács",
            GivenName = "Andrea",
            Nickname = "Andi",
            ZoneInfo = "Europe/Budapest",
            Gender = Gender.Female,
            Locale = "hu-HU",
            Email = "andrea.kovacs@example.com",
            PhoneNumber = "+36 987654321",
            BirthDate = DateTime.Parse("1990-12-01"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 76,
            FamilyName = "Schmidt",
            GivenName = "Lena",
            Nickname = "Lena",
            ZoneInfo = "Europe/Berlin",
            Gender = Gender.Female,
            Locale = "de-DE",
            Email = "lena.schmidt@example.com",
            PhoneNumber = "+49 1234567890",
            BirthDate = DateTime.Parse("1998-05-22"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 77,
            FamilyName = "Fischer",
            GivenName = "Emma",
            Nickname = "EFischer",
            ZoneInfo = "Europe/Berlin",
            Gender = Gender.Female,
            Locale = "de-DE",
            Email = "emma.fischer@example.com",
            PhoneNumber = "+49 123456789",
            BirthDate = DateTime.Parse("1995-05-10"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 78,
            FamilyName = "Santos",
            GivenName = "Miguel",
            Nickname = "Miguel",
            ZoneInfo = "Europe/Lisbon",
            Gender = Gender.Male,
            Locale = "pt-PT",
            Email = "miguel.santos@example.com",
            PhoneNumber = "+351 123456789",
            BirthDate = DateTime.Parse("2001-09-30"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 79,
            FamilyName = "Andersen",
            GivenName = "Emma",
            Nickname = "Emma",
            ZoneInfo = "Europe/Copenhagen",
            Gender = Gender.Female,
            Locale = "da-DK",
            Email = "emma.andersen@example.com",
            PhoneNumber = "+45 12345678",
            BirthDate = DateTime.Parse("1999-07-08"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 80,
            FamilyName = "Kovačević",
            GivenName = "Marko",
            Nickname = "Marko",
            ZoneInfo = "Europe/Belgrade",
            Gender = Gender.Male,
            Locale = "sr-RS",
            Email = "marko.kovacevic@example.com",
            PhoneNumber = "+381 123456789",
            BirthDate = DateTime.Parse("2002-12-17"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 81,
            FamilyName = "Kobakhidze",
            GivenName = "Nino",
            Nickname = "Nino",
            ZoneInfo = "Asia/Tbilisi",
            Gender = Gender.Female,
            Locale = "ka-GE",
            Email = "nino.kobakhidze@example.com",
            PhoneNumber = "+995 123456789",
            BirthDate = DateTime.Parse("1995-03-16"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 82,
            FamilyName = "Kovalenko",
            GivenName = "Oleksandr",
            Nickname = "Alex",
            ZoneInfo = "Europe/Kiev",
            Gender = Gender.Male,
            Locale = "uk-UA",
            Email = "oleksandr.kovalenko@example.com",
            PhoneNumber = "+380 123456789",
            BirthDate = DateTime.Parse("1997-08-25"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 83,
            FamilyName = "Jankauskaitė",
            GivenName = "Gabija",
            Nickname = "Gabija",
            ZoneInfo = "Europe/Vilnius",
            Gender = Gender.Female,
            Locale = "lt-LT",
            Email = "gabija.jankauskaite@example.com",
            PhoneNumber = "+370 12345678",
            BirthDate = DateTime.Parse("1999-11-03"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 84,
            FamilyName = "Nowak",
            GivenName = "Kamil",
            Nickname = "Kamil",
            ZoneInfo = "Europe/Warsaw",
            Gender = Gender.Male,
            Locale = "pl-PL",
            Email = "kamil.nowak@example.com",
            PhoneNumber = "+48 123456789",
            BirthDate = DateTime.Parse("1996-06-12"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 85,
            FamilyName = "Sidarevich",
            GivenName = "Aliaksei",
            Nickname = "Aliaksei",
            ZoneInfo = "Europe/Minsk",
            Gender = Gender.Male,
            Locale = "be-BY",
            Email = "aliaksei.sidarevich@example.com",
            PhoneNumber = "+375 987654321",
            BirthDate = DateTime.Parse("1995-06-30"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 86,
            FamilyName = "Kovalchuk",
            GivenName = "Olga",
            Nickname = "Olga",
            ZoneInfo = "Europe/Kiev",
            Gender = Gender.Female,
            Locale = "uk-UA",
            Email = "olga.kovalchuk@example.com",
            PhoneNumber = "+380 123456789",
            BirthDate = DateTime.Parse("1997-02-28"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 87,
            FamilyName = "Hrytsak",
            GivenName = "Roman",
            Nickname = "Roman",
            ZoneInfo = "Europe/Kiev",
            Gender = Gender.Male,
            Locale = "uk-UA",
            Email = "roman.hrytsak@example.com",
            PhoneNumber = "+380 123456789",
            BirthDate = DateTime.Parse("1996-09-15"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 88,
            FamilyName = "Nowak",
            GivenName = "Kasia",
            Nickname = "Kasia",
            ZoneInfo = "Europe/Warsaw",
            Gender = Gender.Female,
            Locale = "pl-PL",
            Email = "kasia.nowak@example.com",
            PhoneNumber = "+48 123456789",
            BirthDate = DateTime.Parse("1998-12-03"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 89,
            FamilyName = "Kapanadze",
            GivenName = "Nika",
            Nickname = "Nika",
            ZoneInfo = "Asia/Tbilisi",
            Gender = Gender.Female,
            Locale = "ka-GE",
            Email = "nika.kapanadze@example.com",
            PhoneNumber = "+995 123456789",
            BirthDate = DateTime.Parse("1999-06-20"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 90,
            FamilyName = "Jankauskas",
            GivenName = "Tomas",
            Nickname = "Tomas",
            ZoneInfo = "Europe/Vilnius",
            Gender = Gender.Male,
            Locale = "lt-LT",
            Email = "tomas.jankauskas@example.com",
            PhoneNumber = "+370 12345678",
            BirthDate = DateTime.Parse("1997-11-10"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 91,
            FamilyName = "Ivanenko",
            GivenName = "Kateryna",
            Nickname = "Kateryna",
            ZoneInfo = "Europe/Kiev",
            Gender = Gender.Female,
            Locale = "uk-UA",
            Email = "kateryna.ivanenko@example.com",
            PhoneNumber = "+380 123456789",
            BirthDate = DateTime.Parse("1998-07-01"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 92,
            FamilyName = "Kowalski",
            GivenName = "Adam",
            Nickname = "Adam",
            ZoneInfo = "Europe/Warsaw",
            Gender = Gender.Male,
            Locale = "pl-PL",
            Email = "adam.kowalski@example.com",
            PhoneNumber = "+48 123456789",
            BirthDate = DateTime.Parse("1999-04-14"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 93,
            FamilyName = "Petraitis",
            GivenName = "Giedrė",
            Nickname = "Giedrė",
            ZoneInfo = "Europe/Vilnius",
            Gender = Gender.Female,
            Locale = "lt-LT",
            Email = "giedre.petraitis@example.com",
            PhoneNumber = "+370 12345678",
            BirthDate = DateTime.Parse("1997-10-27"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 94,
            FamilyName = "Katsitadze",
            GivenName = "Levan",
            Nickname = "Levan",
            ZoneInfo = "Asia/Tbilisi",
            Gender = Gender.Male,
            Locale = "ka-GE",
            Email = "levan.katsitadze@example.com",
            PhoneNumber = "+995 123456789",
            BirthDate = DateTime.Parse("1996-03-08"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 95,
            FamilyName = "Kovalenko",
            GivenName = "Dmytro",
            Nickname = "Dmytro",
            ZoneInfo = "Europe/Kiev",
            Gender = Gender.Male,
            Locale = "uk-UA",
            Email = "dmytro.kovalenko@example.com",
            PhoneNumber = "+380 123456789",
            BirthDate = DateTime.Parse("1999-12-15"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 96,
            FamilyName = "Schmidt",
            GivenName = "Jonas",
            Nickname = "JSchmidt",
            ZoneInfo = "Europe/Berlin",
            Gender = Gender.Male,
            Locale = "de-DE",
            Email = "jonas.schmidt@example.com",
            PhoneNumber = "+49 123456789",
            BirthDate = DateTime.Parse("1990-10-15"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 97,
            FamilyName = "Virtanen",
            GivenName = "Marko",
            Nickname = "MVirtanen",
            ZoneInfo = "Europe/Helsinki",
            Gender = Gender.Male,
            Locale = "fi-FI",
            Email = "marko.virtanen@example.com",
            PhoneNumber = "+358 123456789",
            BirthDate = DateTime.Parse("1988-07-10"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 98,
            FamilyName = "Müller",
            GivenName = "Anna",
            Nickname = "Anna",
            ZoneInfo = "Europe/Berlin",
            Gender = Gender.Female,
            Locale = "de-DE",
            Email = "anna.muller@example.com",
            PhoneNumber = "+49 123456789",
            BirthDate = DateTime.Parse("1998-08-18"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 99,
            FamilyName = "Rossi",
            GivenName = "Marco",
            Nickname = "Marco",
            ZoneInfo = "Europe/Rome",
            Gender = Gender.Male,
            Locale = "it-IT",
            Email = "marco.rossi@example.com",
            PhoneNumber = "+39 123456789",
            BirthDate = DateTime.Parse("1996-11-02"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 100,
            FamilyName = "Andersen",
            GivenName = "Lise",
            Nickname = "Lise",
            ZoneInfo = "Europe/Copenhagen",
            Gender = Gender.Female,
            Locale = "da-DK",
            Email = "lise.andersen@example.com",
            PhoneNumber = "+45 123456789",
            BirthDate = DateTime.Parse("1999-03-12"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 101,
            FamilyName = "Liepa",
            GivenName = "Anna",
            Nickname = "Anna",
            ZoneInfo = "Europe/Riga",
            Gender = Gender.Female,
            Locale = "lv-LV",
            Email = "anna.liepa@example.com",
            PhoneNumber = "+371 123456789",
            BirthDate = DateTime.Parse("1998-06-05"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 102,
            FamilyName = "Eisenberg",
            GivenName = "Jüri",
            Nickname = "Jüri",
            ZoneInfo = "Europe/Tallinn",
            Gender = Gender.Male,
            Locale = "et-EE",
            Email = "juri.eisenberg@example.com",
            PhoneNumber = "+372 123456789",
            BirthDate = DateTime.Parse("1997-03-20"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 103,
            FamilyName = "Yessenzholov",
            GivenName = "Aidar",
            Nickname = "Aidar",
            ZoneInfo = "Asia/Almaty",
            Gender = Gender.Male,
            Locale = "kk-KZ",
            Email = "aidar.yessenzholov@example.com",
            PhoneNumber = "+7 123456789",
            BirthDate = DateTime.Parse("1996-09-15"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 104,
            FamilyName = "Hakobyan",
            GivenName = "Lilit",
            Nickname = "Lilit",
            ZoneInfo = "Asia/Yerevan",
            Gender = Gender.Female,
            Locale = "hy-AM",
            Email = "lilit.hakobyan@example.com",
            PhoneNumber = "+374 123456789",
            BirthDate = DateTime.Parse("1995-12-03"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 105,
            FamilyName = "Bērziņš",
            GivenName = "Juris",
            Nickname = "Juris",
            ZoneInfo = "Europe/Riga",
            Gender = Gender.Male,
            Locale = "lv-LV",
            Email = "juris.berzins@example.com",
            PhoneNumber = "+371 123456789",
            BirthDate = DateTime.Parse("1999-11-10"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 106,
            FamilyName = "Kask",
            GivenName = "Kristiina",
            Nickname = "Kristiina",
            ZoneInfo = "Europe/Tallinn",
            Gender = Gender.Female,
            Locale = "et-EE",
            Email = "kristiina.kask@example.com",
            PhoneNumber = "+372 123456789",
            BirthDate = DateTime.Parse("1998-04-25"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 107,
            FamilyName = "Sargsyan",
            GivenName = "Ashot",
            Nickname = "Ashot",
            ZoneInfo = "Asia/Yerevan",
            Gender = Gender.Male,
            Locale = "hy-AM",
            Email = "ashot.sargsyan@example.com",
            PhoneNumber = "+374 123456789",
            BirthDate = DateTime.Parse("1997-02-15"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 108,
            FamilyName = "Rahmanov",
            GivenName = "Bakhtiyar",
            Nickname = "Bakhtiyar",
            ZoneInfo = "Asia/Almaty",
            Gender = Gender.Male,
            Locale = "kk-KZ",
            Email = "bakhtiyar.rahmanov@example.com",
            PhoneNumber = "+7 123456789",
            BirthDate = DateTime.Parse("1996-08-20"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 109,
            FamilyName = "Jansone",
            GivenName = "Līga",
            Nickname = "Līga",
            ZoneInfo = "Europe/Riga",
            Gender = Gender.Female,
            Locale = "lv-LV",
            Email = "liga.jansone@example.com",
            PhoneNumber = "+371 123456789",
            BirthDate = DateTime.Parse("1995-10-05"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 110,
            FamilyName = "Kullamaa",
            GivenName = "Jaanika",
            Nickname = "Jaanika",
            ZoneInfo = "Europe/Tallinn",
            Gender = Gender.Female,
            Locale = "et-EE",
            Email = "jaanika.kullamaa@example.com",
            PhoneNumber = "+372 123456789",
            BirthDate = DateTime.Parse("1999-07-12"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 111,
            FamilyName = "Petrovs",
            GivenName = "Māris",
            Nickname = "Māris",
            ZoneInfo = "Europe/Riga",
            Gender = Gender.Male,
            Locale = "lv-LV",
            Email = "maris.petrovs@example.com",
            PhoneNumber = "+371 123456789",
            BirthDate = DateTime.Parse("1998-03-05"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 112,
            FamilyName = "Kangur",
            GivenName = "Mart",
            Nickname = "Mart",
            ZoneInfo = "Europe/Tallinn",
            Gender = Gender.Male,
            Locale = "et-EE",
            Email = "mart.kangur@example.com",
            PhoneNumber = "+372 123456789",
            BirthDate = DateTime.Parse("1997-09-20"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 113,
            FamilyName = "Nurzhanov",
            GivenName = "Aibek",
            Nickname = "Aibek",
            ZoneInfo = "Asia/Almaty",
            Gender = Gender.Male,
            Locale = "kk-KZ",
            Email = "aibek.nurzhanov@example.com",
            PhoneNumber = "+7 123456789",
            BirthDate = DateTime.Parse("1996-12-15"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 114,
            FamilyName = "Avanesyan",
            GivenName = "Anahit",
            Nickname = "Anahit",
            ZoneInfo = "Asia/Yerevan",
            Gender = Gender.Female,
            Locale = "hy-AM",
            Email = "anahit.avanesyan@example.com",
            PhoneNumber = "+374 123456789",
            BirthDate = DateTime.Parse("1995-05-03"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 115,
            FamilyName = "Ozoliņa",
            GivenName = "Līga",
            Nickname = "Līga",
            ZoneInfo = "Europe/Riga",
            Gender = Gender.Female,
            Locale = "lv-LV",
            Email = "liga.ozolina@example.com",
            PhoneNumber = "+371 123456789",
            BirthDate = DateTime.Parse("1999-02-10"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 116,
            FamilyName = "Hakala",
            GivenName = "Sofia",
            Nickname = "Sofia",
            ZoneInfo = "Europe/Helsinki",
            Gender = Gender.Female,
            Locale = "fi-FI",
            Email = "sofia.hakala@example.com",
            PhoneNumber = "+358 123456789",
            BirthDate = DateTime.Parse("1994-04-20"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 117,
            FamilyName = "Zharnasek",
            GivenName = "Alena",
            Nickname = "Firefly",
            ZoneInfo = "Europe/Paris",
            Gender = Gender.Female,
            Locale = "be-BY",
            Email = "alena.zharnasek@example.com",
            PhoneNumber = "+375 123456789",
            BirthDate = DateTime.Parse("1992-10-15"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 118,
            FamilyName = "Johnson",
            GivenName = "Michael",
            Nickname = "MJohnson",
            ZoneInfo = "America/New_York",
            Gender = Gender.Male,
            Locale = "en-US",
            Email = "michael.johnson@example.com",
            PhoneNumber = "+1 123456789",
            BirthDate = DateTime.Parse("1988-08-10"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 119,
            FamilyName = "Kalnina",
            GivenName = "Linda",
            Nickname = "LKalnina",
            ZoneInfo = "Europe/Riga",
            Gender = Gender.Female,
            Locale = "lv-LV",
            Email = "linda.kalnina@example.com",
            PhoneNumber = "+371 12345678",
            BirthDate = DateTime.Parse("1996-02-28"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 120,
            FamilyName = "Silva",
            GivenName = "Camila",
            Nickname = "CSilva",
            ZoneInfo = "America/Buenos_Aires",
            Gender = Gender.Female,
            Locale = "es-AR",
            Email = "camila.silva@example.com",
            PhoneNumber = "+54 987654321",
            BirthDate = DateTime.Parse("1992-07-15"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 121,
            FamilyName = "Ivanović",
            GivenName = "Marko",
            Nickname = "Marko",
            ZoneInfo = "Europe/Zagreb",
            Gender = Gender.Male,
            Locale = "hr-HR",
            Email = "marko.ivanovic@example.com",
            PhoneNumber = "+385 123456789",
            BirthDate = DateTime.Parse("1997-11-05"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 122,
            FamilyName = "Garcia",
            GivenName = "Sofia",
            Nickname = "Sof",
            ZoneInfo = "Europe/Madrid",
            Gender = Gender.Female,
            Locale = "es-ES",
            Email = "sofia.garcia@example.com",
            PhoneNumber = "+34 1234567890",
            BirthDate = DateTime.Parse("1998-11-25"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 123,
            FamilyName = "Schmidt",
            GivenName = "Max",
            Nickname = "Max",
            ZoneInfo = "Europe/Berlin",
            Gender = Gender.Male,
            Locale = "de-DE",
            Email = "max.schmidt@example.com",
            PhoneNumber = "+49 123456789",
            BirthDate = DateTime.Parse("1995-02-03"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 124,
            FamilyName = "Popescu",
            GivenName = "Maria",
            Nickname = "Maria",
            ZoneInfo = "Europe/Bucharest",
            Gender = Gender.Female,
            Locale = "ro-RO",
            Email = "maria.popescu@example.com",
            PhoneNumber = "+40 123456789",
            BirthDate = DateTime.Parse("1998-09-10"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 125,
            FamilyName = "Kovačić",
            GivenName = "Ivan",
            Nickname = "Ivan",
            ZoneInfo = "Europe/Zagreb",
            Gender = Gender.Male,
            Locale = "hr-HR",
            Email = "ivan.kovacic@example.com",
            PhoneNumber = "+385 123456789",
            BirthDate = DateTime.Parse("1999-04-12"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 126,
            FamilyName = "Novák",
            GivenName = "Petr",
            Nickname = "Petr",
            ZoneInfo = "Europe/Prague",
            Gender = Gender.Male,
            Locale = "cs-CZ",
            Email = "petr.novak@example.com",
            PhoneNumber = "+420 123456789",
            BirthDate = DateTime.Parse("1996-07-15"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 127,
            FamilyName = "Kowalska",
            GivenName = "Anna",
            Nickname = "Anna",
            ZoneInfo = "Europe/Warsaw",
            Gender = Gender.Female,
            Locale = "pl-PL",
            Email = "anna.kowalska@example.com",
            PhoneNumber = "+48 123456789",
            BirthDate = DateTime.Parse("1997-03-20"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 128,
            FamilyName = "Horvat",
            GivenName = "Ivan",
            Nickname = "Ivan",
            ZoneInfo = "Europe/Zagreb",
            Gender = Gender.Male,
            Locale = "hr-HR",
            Email = "ivan.horvat@example.com",
            PhoneNumber = "+385 123456789",
            BirthDate = DateTime.Parse("1998-11-05"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 129,
            FamilyName = "Novak",
            GivenName = "Maja",
            Nickname = "Maja",
            ZoneInfo = "Europe/Ljubljana",
            Gender = Gender.Female,
            Locale = "sl-SI",
            Email = "maja.novak@example.com",
            PhoneNumber = "+386 123456789",
            BirthDate = DateTime.Parse("1996-09-10"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 130,
            FamilyName = "Andersson",
            GivenName = "Benjamin",
            Nickname = "BAndersson",
            ZoneInfo = "Europe/Stockholm",
            Gender = Gender.Male,
            Locale = "sv-SE",
            Email = "benjamin.andersson@example.com",
            PhoneNumber = "+46 123456789",
            BirthDate = DateTime.Parse("1993-09-05"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 131,
            FamilyName = "Santos",
            GivenName = "Carlos",
            Nickname = "CSantos",
            ZoneInfo = "America/Sao_Paulo",
            Gender = Gender.Male,
            Locale = "pt-BR",
            Email = "carlos.santos@example.com",
            PhoneNumber = "+55 123456789",
            BirthDate = DateTime.Parse("1990-12-15"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 132,
            FamilyName = "Garcia",
            GivenName = "Maria",
            Nickname = "Maria",
            ZoneInfo = "America/Los_Angeles",
            Gender = Gender.Female,
            Locale = "es-ES",
            Email = "maria.garcia@example.com",
            PhoneNumber = "+1 123456789",
            BirthDate = DateTime.Parse("1996-12-10"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 133,
            FamilyName = "Andersson",
            GivenName = "Alexander",
            Nickname = "Alexander",
            ZoneInfo = "Europe/Stockholm",
            Gender = Gender.Male,
            Locale = "sv-SE",
            Email = "alexander.andersson@example.com",
            PhoneNumber = "+46 123456789",
            BirthDate = DateTime.Parse("1993-11-02"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 134,
            FamilyName = "Kim",
            GivenName = "Ji-hyun",
            Nickname = "Ji-hyun",
            ZoneInfo = "Asia/Seoul",
            Gender = Gender.Female,
            Locale = "ko-KR",
            Email = "ji-hyun.kim@example.com",
            PhoneNumber = "+82 123456789",
            BirthDate = DateTime.Parse("1998-06-05"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 135,
            FamilyName = "Fernández",
            GivenName = "Carlos",
            Nickname = "Carlos",
            ZoneInfo = "America/Argentina/Buenos_Aires",
            Gender = Gender.Male,
            Locale = "es-AR",
            Email = "carlos.fernandez@example.com",
            PhoneNumber = "+54 123456789",
            BirthDate = DateTime.Parse("1996-10-15"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 136,
            FamilyName = "Berzins",
            GivenName = "Roberts",
            Nickname = "RBerzins",
            ZoneInfo = "Europe/Riga",
            Gender = Gender.Male,
            Locale = "lv-LV",
            Email = "roberts.berzins@example.com",
            PhoneNumber = "+371 12345678",
            BirthDate = DateTime.Parse("1992-07-20"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 137,
            FamilyName = "Sato",
            GivenName = "Kenji",
            Nickname = "Kenji",
            ZoneInfo = "Asia/Tokyo",
            Gender = Gender.Male,
            Locale = "ja-JP",
            Email = "kenji.sato@example.com",
            PhoneNumber = "+81 123456789",
            BirthDate = DateTime.Parse("1995-11-10"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 138,
            FamilyName = "Silva",
            GivenName = "João",
            Nickname = "João",
            ZoneInfo = "America/Sao_Paulo",
            Gender = Gender.Male,
            Locale = "pt-BR",
            Email = "joao.silva@example.com",
            PhoneNumber = "+55 123456789",
            BirthDate = DateTime.Parse("1996-02-03"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 139,
            FamilyName = "López",
            GivenName = "Ana",
            Nickname = "Ana",
            ZoneInfo = "America/Mexico_City",
            Gender = Gender.Female,
            Locale = "es-MX",
            Email = "ana.lopez@example.com",
            PhoneNumber = "+52 123456789",
            BirthDate = DateTime.Parse("1997-09-10"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 140,
            FamilyName = "Ramos",
            GivenName = "Miguel",
            Nickname = "Miguel",
            ZoneInfo = "America/Los_Angeles",
            Gender = Gender.Male,
            Locale = "es-ES",
            Email = "miguel.ramos@example.com",
            PhoneNumber = "+1 123456789",
            BirthDate = DateTime.Parse("1998-12-12"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 141,
            FamilyName = "Schmidt",
            GivenName = "Anna",
            Nickname = "Anna",
            ZoneInfo = "Europe/Berlin",
            Gender = Gender.Female,
            Locale = "de-DE",
            Email = "anna.schmidt@example.com",
            PhoneNumber = "+49 123456789",
            BirthDate = DateTime.Parse("1990-05-01"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 142,
            FamilyName = "Dupont",
            GivenName = "Sophie",
            Nickname = "Sophie",
            ZoneInfo = "Europe/Paris",
            Gender = Gender.Female,
            Locale = "fr-FR",
            Email = "sophie.dupont@example.com",
            PhoneNumber = "+33 123456789",
            BirthDate = DateTime.Parse("1995-07-10"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 143,
            FamilyName = "Müller",
            GivenName = "Thomas",
            Nickname = "Thomas",
            ZoneInfo = "Europe/Berlin",
            Gender = Gender.Male,
            Locale = "de-DE",
            Email = "thomas.muller@example.com",
            PhoneNumber = "+49 123456789",
            BirthDate = DateTime.Parse("1993-11-05"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 144,
            FamilyName = "Rossi",
            GivenName = "Giulia",
            Nickname = "Giulia",
            ZoneInfo = "Europe/Rome",
            Gender = Gender.Female,
            Locale = "it-IT",
            Email = "giulia.rossi@example.com",
            PhoneNumber = "+39 123456789",
            BirthDate = DateTime.Parse("1992-09-10"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 145,
            FamilyName = "Lee",
            GivenName = "Jiyeon",
            Nickname = "JLee",
            ZoneInfo = "Asia/Seoul",
            Gender = Gender.Female,
            Locale = "ko-KR",
            Email = "jiyeon.lee@example.com",
            PhoneNumber = "+82 123456789",
            BirthDate = DateTime.Parse("1990-12-25"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 146,
            FamilyName = "Kuznetsova",
            GivenName = "Emilija",
            Nickname = "EKuznetsova",
            ZoneInfo = "Europe/Moscow",
            Gender = Gender.Female,
            Locale = "ru-RU",
            Email = "emilija.kuznetsova@example.com",
            PhoneNumber = "+7 123456789",
            BirthDate = DateTime.Parse("1993-12-01"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 147,
            FamilyName = "Müller",
            GivenName = "Hans",
            Nickname = "Hans",
            ZoneInfo = "Europe/Berlin",
            Gender = Gender.Male,
            Locale = "de-DE",
            Email = "hans.muller@example.com",
            PhoneNumber = "+49 123456789",
            BirthDate = DateTime.Parse("1995-02-14"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 148,
            FamilyName = "Rousseau",
            GivenName = "Jean",
            Nickname = "Jean",
            ZoneInfo = "Europe/Paris",
            Gender = Gender.Male,
            Locale = "fr-FR",
            Email = "jean.rousseau@example.com",
            PhoneNumber = "+33 123456789",
            BirthDate = DateTime.Parse("1993-06-19"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 149,
            FamilyName = "Bianchi",
            GivenName = "Giuseppe",
            Nickname = "Giuseppe",
            ZoneInfo = "Europe/Rome",
            Gender = Gender.Male,
            Locale = "it-IT",
            Email = "giuseppe.bianchi@example.com",
            PhoneNumber = "+39 123456789",
            BirthDate = DateTime.Parse("1994-10-30"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 150,
            FamilyName = "Schneider",
            GivenName = "Sabine",
            Nickname = "Sabine",
            ZoneInfo = "Europe/Berlin",
            Gender = Gender.Female,
            Locale = "de-DE",
            Email = "sabine.schneider@example.com",
            PhoneNumber = "+49 123456789",
            BirthDate = DateTime.Parse("1995-12-25"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 151,
            FamilyName = "Garcia",
            GivenName = "Manuel",
            Nickname = "Manuel",
            ZoneInfo = "Europe/Madrid",
            Gender = Gender.Male,
            Locale = "es-ES",
            Email = "manuel.garcia@example.com",
            PhoneNumber = "+34 123456789",
            BirthDate = DateTime.Parse("1993-09-17"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 152,
            FamilyName = "Weber",
            GivenName = "Laura",
            Nickname = "Laura",
            ZoneInfo = "Europe/Berlin",
            Gender = Gender.Female,
            Locale = "de-DE",
            Email = "laura.weber@example.com",
            PhoneNumber = "+49 123456789",
            BirthDate = DateTime.Parse("1992-04-22"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 153,
            FamilyName = "Lefevre",
            GivenName = "Julien",
            Nickname = "Julien",
            ZoneInfo = "Europe/Paris",
            Gender = Gender.Male,
            Locale = "fr-FR",
            Email = "julien.lefevre@example.com",
            PhoneNumber = "+33 123456789",
            BirthDate = DateTime.Parse("1994-03-08"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 154,
            FamilyName = "Romano",
            GivenName = "Francesca",
            Nickname = "Francesca",
            ZoneInfo = "Europe/Rome",
            Gender = Gender.Female,
            Locale = "it-IT",
            Email = "francesca.romano@example.com",
            PhoneNumber = "+39 123456789",
            BirthDate = DateTime.Parse("1993-02-12"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 155,
            FamilyName = "Müller",
            GivenName = "Stefan",
            Nickname = "Stefan",
            ZoneInfo = "Europe/Berlin",
            Gender = Gender.Male,
            Locale = "de-DE",
            Email = "stefan.muller@example.com",
            PhoneNumber = "+49 123456789",
            BirthDate = DateTime.Parse("1994-07-29"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 156,
            FamilyName = "Jansen",
            GivenName = "Emma",
            Nickname = "EJansen",
            ZoneInfo = "Europe/Amsterdam",
            Gender = Gender.Female,
            Locale = "nl-NL",
            Email = "emma.jansen@example.com",
            PhoneNumber = "+31 987654321",
            BirthDate = DateTime.Parse("1996-02-28"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 157,
            FamilyName = "Olsen",
            GivenName = "Erik",
            Nickname = "Erik",
            ZoneInfo = "Europe/Oslo",
            Gender = Gender.Male,
            Locale = "nb-NO",
            Email = "erik.olsen@example.com",
            PhoneNumber = "+47 123456789",
            BirthDate = DateTime.Parse("1992-09-25"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 158,
            FamilyName = "Johansson",
            GivenName = "Maja",
            Nickname = "Maja",
            ZoneInfo = "Europe/Stockholm",
            Gender = Gender.Female,
            Locale = "sv-SE",
            Email = "maja.johansson@example.com",
            PhoneNumber = "+46 123456789",
            BirthDate = DateTime.Parse("1994-03-18"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 159,
            FamilyName = "Hansen",
            GivenName = "Andreas",
            Nickname = "Andreas",
            ZoneInfo = "Europe/Oslo",
            Gender = Gender.Male,
            Locale = "nb-NO",
            Email = "andreas.hansen@example.com",
            PhoneNumber = "+47 123456789",
            BirthDate = DateTime.Parse("1993-12-12"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 160,
            FamilyName = "Nielsen",
            GivenName = "Sofia",
            Nickname = "Sofia",
            ZoneInfo = "Europe/Helsinki",
            Gender = Gender.Female,
            Locale = "fi-FI",
            Email = "sofia.nielsen@example.com",
            PhoneNumber = "+358 123456789",
            BirthDate = DateTime.Parse("1992-08-20"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 161,
            FamilyName = "Kim",
            GivenName = "Soo-Min",
            Nickname = "SKim",
            ZoneInfo = "Asia/Seoul",
            Gender = Gender.Female,
            Locale = "ko-KR",
            Email = "soo.min.kim@example.com",
            PhoneNumber = "+82 9876543210",
            BirthDate = DateTime.Parse("1993-03-25"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 162,
            FamilyName = "Jónsdóttir",
            GivenName = "Eva",
            Nickname = "Eva",
            ZoneInfo = "Atlantic/Reykjavik",
            Gender = Gender.Female,
            Locale = "is-IS",
            Email = "eva.jonsdottir@example.com",
            PhoneNumber = "+354 123456789",
            BirthDate = DateTime.Parse("1992-11-11"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 163,
            FamilyName = "Pedersen",
            GivenName = "Lars",
            Nickname = "Lars",
            ZoneInfo = "America/Godthab",
            Gender = Gender.Male,
            Locale = "kl-GL",
            Email = "lars.pedersen@example.com",
            PhoneNumber = "+299 123456789",
            BirthDate = DateTime.Parse("1994-05-06"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 164,
            FamilyName = "O'Brien",
            GivenName = "Aoife",
            Nickname = "Aoife",
            ZoneInfo = "Europe/Dublin",
            Gender = Gender.Female,
            Locale = "en-IE",
            Email = "aoife.obrien@example.com",
            PhoneNumber = "+353 123456789",
            BirthDate = DateTime.Parse("1993-04-16"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 165,
            FamilyName = "Hansson",
            GivenName = "Sofie",
            Nickname = "Sofie",
            ZoneInfo = "Europe/Copenhagen",
            Gender = Gender.Female,
            Locale = "da-DK",
            Email = "sofie.hansson@example.com",
            PhoneNumber = "+45 123456789",
            BirthDate = DateTime.Parse("1994-09-09"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 166,
            FamilyName = "Georgiou",
            GivenName = "Maria",
            Nickname = "Maria",
            ZoneInfo = "Asia/Nicosia",
            Gender = Gender.Female,
            Locale = "el-CY",
            Email = "maria.georgiou@example.com",
            PhoneNumber = "+357 123456789",
            BirthDate = DateTime.Parse("1993-12-01"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 167,
            FamilyName = "Novák",
            GivenName = "Ján",
            Nickname = "Ján",
            ZoneInfo = "Europe/Bratislava",
            Gender = Gender.Male,
            Locale = "sk-SK",
            Email = "jan.novak@example.com",
            PhoneNumber = "+421 123456789",
            BirthDate = DateTime.Parse("1992-10-10"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 168,
            FamilyName = "Kovač",
            GivenName = "Ana",
            Nickname = "Ana",
            ZoneInfo = "Europe/Ljubljana",
            Gender = Gender.Female,
            Locale = "sl-SI",
            Email = "ana.kovac@example.com",
            PhoneNumber = "+386 123456789",
            BirthDate = DateTime.Parse("1993-07-05"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 169,
            FamilyName = "Horvat",
            GivenName = "Marko",
            Nickname = "Marko",
            ZoneInfo = "Europe/Zagreb",
            Gender = Gender.Male,
            Locale = "hr-HR",
            Email = "marko.horvat@example.com",
            PhoneNumber = "+385 123456789",
            BirthDate = DateTime.Parse("1992-05-25"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 170,
            FamilyName = "Christodoulou",
            GivenName = "Sophia",
            Nickname = "Sophia",
            ZoneInfo = "Asia/Nicosia",
            Gender = Gender.Female,
            Locale = "el-CY",
            Email = "sophia.christodoulou@example.com",
            PhoneNumber = "+357 123456789",
            BirthDate = DateTime.Parse("1994-08-15"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 171,
            FamilyName = "García",
            GivenName = "Marta",
            Nickname = "Marta",
            ZoneInfo = "Europe/Madrid",
            Gender = Gender.Female,
            Locale = "es-ES",
            Email = "marta.garcia@example.com",
            PhoneNumber = "+34 123456789",
            BirthDate = DateTime.Parse("1992-09-12"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 172,
            FamilyName = "Davis",
            GivenName = "Emily",
            Nickname = "Emily",
            ZoneInfo = "America/Los_Angeles",
            Gender = Gender.Female,
            Locale = "en-US",
            Email = "emily.davis@example.com",
            PhoneNumber = "+1 123456789",
            BirthDate = DateTime.Parse("1990-07-15"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 173,
            FamilyName = "Petrauskas",
            GivenName = "Elena",
            Nickname = "EPetrauskas",
            ZoneInfo = "Europe/Vilnius",
            Gender = Gender.Female,
            Locale = "lt-LT",
            Email = "elena.petrauskas@example.com",
            PhoneNumber = "+370 987654321",
            BirthDate = DateTime.Parse("1990-05-20"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 174,
            FamilyName = "Smith",
            GivenName = "James",
            Nickname = "James",
            ZoneInfo = "Europe/London",
            Gender = Gender.Male,
            Locale = "en-GB",
            Email = "james.smith@example.com",
            PhoneNumber = "+44 123456789",
            BirthDate = DateTime.Parse("1993-03-08"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 175,
            FamilyName = "Andersen",
            GivenName = "Lena",
            Nickname = "Lena",
            ZoneInfo = "Atlantic/Reykjavik",
            Gender = Gender.Female,
            Locale = "is-IS",
            Email = "lena.andersen@example.com",
            PhoneNumber = "+354 123456789",
            BirthDate = DateTime.Parse("1994-07-29"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 176,
            FamilyName = "Dubois",
            GivenName = "Sophie",
            Nickname = "Sophie",
            ZoneInfo = "Europe/Paris",
            Gender = Gender.Female,
            Locale = "fr-FR",
            Email = "sophie.dubois@example.com",
            PhoneNumber = "+33 123456789",
            BirthDate = DateTime.Parse("1992-10-05"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 177,
            FamilyName = "González",
            GivenName = "Sergio",
            Nickname = "Sergio",
            ZoneInfo = "Europe/Madrid",
            Gender = Gender.Male,
            Locale = "es-ES",
            Email = "sergio.gonzalez@example.com",
            PhoneNumber = "+34 123456789",
            BirthDate = DateTime.Parse("1993-09-18"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 178,
            FamilyName = "Larsen",
            GivenName = "Maja",
            Nickname = "Maja",
            ZoneInfo = "Europe/Copenhagen",
            Gender = Gender.Female,
            Locale = "da-DK",
            Email = "maja.larsen@example.com",
            PhoneNumber = "+45 123456789",
            BirthDate = DateTime.Parse("1992-12-15"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 179,
            FamilyName = "Silva",
            GivenName = "Carlos",
            Nickname = "Carlos",
            ZoneInfo = "Europe/Lisbon",
            Gender = Gender.Male,
            Locale = "pt-PT",
            Email = "carlos.silva@example.com",
            PhoneNumber = "+351 123456789",
            BirthDate = DateTime.Parse("1993-06-28"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 180,
            FamilyName = "Kazlauskaitė",
            GivenName = "Gabija",
            Nickname = "GKazlauskaitė",
            ZoneInfo = "Europe/Vilnius",
            Gender = Gender.Female,
            Locale = "lt-LT",
            Email = "gabija.kazlauskaite@example.com",
            PhoneNumber = "+370 987654321",
            BirthDate = DateTime.Parse("1993-08-15"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 181,
            FamilyName = "Jansen",
            GivenName = "Lotte",
            Nickname = "Lotte",
            ZoneInfo = "Europe/Amsterdam",
            Gender = Gender.Female,
            Locale = "nl-NL",
            Email = "lotte.jansen@example.com",
            PhoneNumber = "+31 123456789",
            BirthDate = DateTime.Parse("1992-07-02"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 182,
            FamilyName = "Müller",
            GivenName = "Max",
            Nickname = "Max",
            ZoneInfo = "Europe/Berlin",
            Gender = Gender.Male,
            Locale = "de-DE",
            Email = "max.muller@example.com",
            PhoneNumber = "+49 123456789",
            BirthDate = DateTime.Parse("1993-03-25"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 183,
            FamilyName = "Rossi",
            GivenName = "Francesca",
            Nickname = "Francesca",
            ZoneInfo = "Europe/Rome",
            Gender = Gender.Female,
            Locale = "it-IT",
            Email = "francesca.rossi@example.com",
            PhoneNumber = "+39 123456789",
            BirthDate = DateTime.Parse("1992-12-20"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 184,
            FamilyName = "Smith",
            GivenName = "Oliver",
            Nickname = "Oliver",
            ZoneInfo = "Europe/London",
            Gender = Gender.Male,
            Locale = "en-GB",
            Email = "oliver.smith@example.com",
            PhoneNumber = "+44 123456789",
            BirthDate = DateTime.Parse("1993-09-14"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 185,
            FamilyName = "Wójcik",
            GivenName = "Jan",
            Nickname = "JKowalski",
            ZoneInfo = "Atlantic/Reykjavik",
            Gender = Gender.Male,
            Locale = "pl-PL",
            Email = "jan.wojcik@example.com",
            PhoneNumber = "+48 987654321",
            BirthDate = DateTime.Parse("1988-12-10"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 186,
            FamilyName = "Dubois",
            GivenName = "Luc",
            Nickname = "Luc",
            ZoneInfo = "Europe/Paris",
            Gender = Gender.Male,
            Locale = "fr-FR",
            Email = "luc.dubois@example.com",
            PhoneNumber = "+33 123456789",
            BirthDate = DateTime.Parse("1992-11-09"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 187,
            FamilyName = "González",
            GivenName = "Laura",
            Nickname = "Laura",
            ZoneInfo = "Europe/Madrid",
            Gender = Gender.Female,
            Locale = "es-ES",
            Email = "laura.gonzalez@example.com",
            PhoneNumber = "+34 123456789",
            BirthDate = DateTime.Parse("1993-12-27"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 188,
            FamilyName = "Larsen",
            GivenName = "Mathias",
            Nickname = "Mathias",
            ZoneInfo = "Europe/Copenhagen",
            Gender = Gender.Male,
            Locale = "da-DK",
            Email = "mathias.larsen@example.com",
            PhoneNumber = "+45 123456789",
            BirthDate = DateTime.Parse("1992-10-18"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 189,
            FamilyName = "Silva",
            GivenName = "Mariana",
            Nickname = "Mariana",
            ZoneInfo = "Europe/Lisbon",
            Gender = Gender.Female,
            Locale = "pt-PT",
            Email = "mariana.silva@example.com",
            PhoneNumber = "+351 123456789",
            BirthDate = DateTime.Parse("1993-07-11"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 190,
            FamilyName = "Andersson",
            GivenName = "Oscar",
            Nickname = "Oscar",
            ZoneInfo = "Europe/Stockholm",
            Gender = Gender.Male,
            Locale = "sv-SE",
            Email = "oscar.andersson@example.com",
            PhoneNumber = "+46 123456789",
            BirthDate = DateTime.Parse("1994-11-25"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 191,
            FamilyName = "Jansen",
            GivenName = "Daan",
            Nickname = "Daan",
            ZoneInfo = "Europe/Amsterdam",
            Gender = Gender.Male,
            Locale = "nl-NL",
            Email = "daan.jansen@example.com",
            PhoneNumber = "+31 123456789",
            BirthDate = DateTime.Parse("1992-08-14"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 192,
            FamilyName = "Müller",
            GivenName = "Hannah",
            Nickname = "Hannah",
            ZoneInfo = "Europe/Berlin",
            Gender = Gender.Female,
            Locale = "de-DE",
            Email = "hannah.muller@example.com",
            PhoneNumber = "+49 123456789",
            BirthDate = DateTime.Parse("1993-05-07"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 193,
            FamilyName = "Rossi",
            GivenName = "Giovanni",
            Nickname = "Giovanni",
            ZoneInfo = "Europe/Rome",
            Gender = Gender.Male,
            Locale = "it-IT",
            Email = "giovanni.rossi@example.com",
            PhoneNumber = "+39 123456789",
            BirthDate = DateTime.Parse("1992-09-30"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 194,
            FamilyName = "Smith",
            GivenName = "Emily",
            Nickname = "Emily",
            ZoneInfo = "Europe/London",
            Gender = Gender.Female,
            Locale = "en-GB",
            Email = "emily.smith@example.com",
            PhoneNumber = "+44 123456789",
            BirthDate = DateTime.Parse("1993-11-16"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 195,
            FamilyName = "Andersen",
            GivenName = "Olivia",
            Nickname = "Olivia",
            ZoneInfo = "Atlantic/Reykjavik",
            Gender = Gender.Female,
            Locale = "is-IS",
            Email = "olivia.andersen@example.com",
            PhoneNumber = "+354 123456789",
            BirthDate = DateTime.Parse("1994-12-13"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 196,
            FamilyName = "Dubois",
            GivenName = "Emma",
            Nickname = "Emma",
            ZoneInfo = "Europe/Paris",
            Gender = Gender.Female,
            Locale = "fr-FR",
            Email = "emma.dubois@example.com",
            PhoneNumber = "+33 123456789",
            BirthDate = DateTime.Parse("1992-12-11"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 197,
            FamilyName = "González",
            GivenName = "Sofía",
            Nickname = "Sofía",
            ZoneInfo = "Europe/Madrid",
            Gender = Gender.Female,
            Locale = "es-ES",
            Email = "sofia.gonzalez@example.com",
            PhoneNumber = "+34 123456789",
            BirthDate = DateTime.Parse("1993-10-27"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 198,
            FamilyName = "Larsen",
            GivenName = "William",
            Nickname = "William",
            ZoneInfo = "Europe/Copenhagen",
            Gender = Gender.Male,
            Locale = "da-DK",
            Email = "william.larsen@example.com",
            PhoneNumber = "+45 123456789",
            BirthDate = DateTime.Parse("1992-09-17"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 199,
            FamilyName = "Silva",
            GivenName = "Matilde",
            Nickname = "Matilde",
            ZoneInfo = "Europe/Lisbon",
            Gender = Gender.Female,
            Locale = "pt-PT",
            Email = "matilde.silva@example.com",
            PhoneNumber = "+351 123456789",
            BirthDate = DateTime.Parse("1993-11-04"),
            Role = Role.Default,
        },
        new UserDetails
        {
            Id = 200,
            FamilyName = "Andersson",
            GivenName = "Noah",
            Nickname = "Noah",
            ZoneInfo = "Europe/Stockholm",
            Gender = Gender.Male,
            Locale = "sv-SE",
            Email = "noah.andersson@example.com",
            PhoneNumber = "+46 123456789",
            BirthDate = DateTime.Parse("1994-12-27"),
            Role = Role.Default,
        },
    };
}
